language: node_js
branches:
  only:
  - master
cache:
  bundler: true
  directories:
  - node_modules
node_js:
  - "8.0.0"
before_script:
  - npm install -g webpack
  - npm install -g gulp-cli
script:
  - NODE_ENV=production webpack -p
  - gulp
deploy:
  provider: surge
  domain: pepper.ink
  skip_cleanup: true